server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    username: postgres
    password: "root"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 10000
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
      key-prefix: employee
      time-to-live: 60000
    type: redis

